/**
 * The shared checks module's public contract (SPEC §5, §8; FR-7, FR-8).
 *
 * These types are the **stable API** the registry service imports verbatim
 * (`@gridmason/cli/checks`) and that the later L-E2 checks (SDK-adherence #12,
 * dependency-DAG + report #13) extend. Keep them additive: a new check adds a
 * {@link Check} to the registry and, when it needs more input, an *optional*
 * field to {@link CheckContext} — never a breaking change to what is here.
 *
 * A check is a **pure** function of its {@link CheckContext}: same input, same
 * results, no filesystem or network of its own. The CLI (`gridmason lint`) and
 * the registry each build the context — reading `manifest.json`, resolving the
 * target registry — and hand it to the identical check code, so "local green
 * predicts review-pass" holds by construction (SPEC §8, "one implementation").
 */

/** A single check's verdict severity. `fail` is the only status that fails a run. */
export type CheckStatus = 'pass' | 'warn' | 'fail';

/**
 * Everything a check reads to make its decision. Built by the caller (the CLI or
 * the registry), never by a check. Grows by *optional* fields as later checks
 * need more input (e.g. #12's source files); existing checks ignore what they do
 * not read, so additions never break a consumer.
 */
export interface CheckContext {
  /**
   * The parsed `manifest.json` under review, as `unknown` because it is
   * **untrusted** — a check must not assume it is a well-formed {@link
   * import('@gridmason/protocol').Manifest}. The `manifest.schema` check is the
   * gate that validates it; shape-dependent checks read defensively.
   */
  readonly manifest: unknown;
  /**
   * Target registry for a registry-aware check (`gridmason lint --registry`).
   * Phase A checks ignore it; the capability-diff / DAG-against-registry checks
   * (Phase B) read it.
   */
  readonly registry?: string;
}

/**
 * One finding from a check. A check emits a single `pass` when clean, or one or
 * more `warn`/`fail` findings when not — so a run's results enumerate every
 * check that ran, not only the failures.
 */
export interface CheckResult {
  /** The {@link Check.id} that produced this finding, so output and registry review align. */
  readonly id: string;
  readonly status: CheckStatus;
  /** Human-readable, specific to this finding (names the offending field/value). */
  readonly message: string;
  /** How to fix *this* finding; surfaced in output and the check-id reference (#14). */
  readonly hint?: string;
}

/**
 * A single check: stable identity + metadata + a pure {@link run}. The registry
 * (`checks`) is an array of these; `gridmason lint` and the registry both run the
 * same objects. The check-id reference page (#14) is generated by iterating the
 * registry and reading `id` / `title` / `rationale`.
 */
export interface Check {
  /**
   * Stable, dotted check id (`<group>.<slug>`, e.g. `manifest.schema`). Echoed by
   * every {@link CheckResult} it emits and by registry review findings. Never
   * renamed once shipped — see the scheme in `docs/checks.md`.
   */
  readonly id: string;
  /** Short human title (`manifest schema`) for output headers and the reference page. */
  readonly title: string;
  /** Why this check exists — one or two sentences, seeds the reference page (#14). */
  readonly rationale: string;
  /** Run the check against `ctx`, returning its findings (never throws). */
  run(ctx: CheckContext): CheckResult[];
}
